config:
  project: NeuronBridge
  stage: ${opt:stage, "cgdev"}
  version: 2.0.0
  libraryBucket: janelia-flylight-color-depth-dev
  libraryThumbnailsBucket: janelia-flylight-color-depth-thumbnails-dev
  alignmentTemplatesBucket: janelia-flylight-color-depth-dev
  searchBucket: janelia-neuronbridge-searches-dev
  perDaySearchLimits: ${env:PER_DAY_SEARCH_LIMITS, 100}
  concurrentSearchLimits: ${env:CONCURRENT_SEARCH_LIMITS, 1}
  tracing: true
  debug: true
