config:
  project: NeuronBridge
  stage: ${opt:stage, 'dev'}
  version: 2.0.0
  libraryBucket: ${env:IMAGE_DATA_BUCKET, 'janelia-flylight-color-depth-dev'}
  pppmBucket: ${env:PPP_DATA_BUCKET, 'janelia-ppp-match-dev'}
  libraryThumbnailsBucket: ${env:IMAGE_THUMBNAILS_BUCKET, 'janelia-flylight-color-depth-thumbnails-dev'}
  alignmentTemplatesBucket: ${env:ALIGN_TEMPLATES_BUCKET, 'janelia-flylight-color-depth-dev'}
  searchBucket: janelia-neuronbridge-search-${opt:stage, 'dev'}
  downloadBucket: janelia-neuronbridge-downloads-${opt:stage, 'dev'}
  dataBucket: janelia-neuronbridge-data-${opt:stage, 'dev'}
  perDaySearchLimits: ${env:PER_DAY_SEARCH_LIMITS, 100}
  perDayAlignmentLimits: ${env:PER_DAY_ALIGNMENT_LIMITS, 5}
  concurrentSearchLimits: ${env:CONCURRENT_SEARCH_LIMITS, 1}
  concurrentAlignmentLimits: ${env:CONCURRENT_ALIGNMENT_LIMITS, 1}
  tracing: true
  debug: ${env:DEBUG, false}
