config:
  project: NeuronBridge
  stage: ${opt:stage, "tkjsdev"}
  version: 2.0.0
  libraryBucket: janelia-flylight-color-depth-dev
  libraryThumbnailsBucket: janelia-flylight-color-depth-thumbnails-dev
  alignmentTemplatesBucket: janelia-flylight-color-depth-dev
  searchBucket: janelia-neuronbridge-masks-tkdev
  tracing: true
  debug: true
