config:
  project: NeuronBridge
  stage: ${opt:stage, 'dev'}
  version: 3.0.0
  pppmBucket: janelia-ppp-match-${env:SEARCH_DATA_LEVEL, opt:stage, 'dev'}
  alignmentTemplatesBucket: ${env:ALIGN_TEMPLATES_BUCKET, 'janelia-flylight-color-depth-dev'}
  searchBucket: janelia-neuronbridge-search-${opt:stage, 'dev'}
  downloadBucket: janelia-neuronbridge-downloads-${opt:stage, 'dev'}
  dataBucket: janelia-neuronbridge-data-${env:SEARCH_DATA_LEVEL, opt:stage, 'dev'}
  perDaySearchLimits: ${env:PER_DAY_SEARCH_LIMITS, 100}
  perDayAlignmentLimits: ${env:PER_DAY_ALIGNMENT_LIMITS, 10}
  concurrentSearchLimits: ${env:CONCURRENT_SEARCH_LIMITS, 1}
  concurrentAlignmentLimits: ${env:CONCURRENT_ALIGNMENT_LIMITS, 1}

  searchBatchSize: 40
  searchParallelization: 5000
  cdsTimeoutInSeconds: 400

  publishedNamesDb:
    dev: 'v3.0.0'
    val: 'v2.4.0'
    prod: 'v2.4.0'
    devpre: 'v3.0.0'
    prodpre: 'v3.0.0'
    other: 'v2.4.0'
  # determines if users can create their own account on a site
  disableAccountCreation:
    dev: true
    val: true
    prod: false
    devpre: true
    prodpre: false
    other: true
  # we shouldn't need backups on any stage apart from production.
  enableBackups:
    prod: true
    other: false

  tracing: true
  debug: ${env:DEBUG, false}
