env:
  node: true
  es2021: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: off
  radix: off
  semi: error
  no-trailing-spaces: error
  block-spacing: error
