env:
  node: true
  es2021: true
  "jest/globals": true
extends:
  - eslint:recommended
parser: '@babel/eslint-parser'  
parserOptions:
  ecmaVersion: 12
  sourceType: module
  requireConfigFile: false
rules:
  no-console: off
  radix: off
  semi: error
  no-trailing-spaces: error
  block-spacing: error
plugins:
  - jest
