env:
  node: true
  commonjs: true
  es2021: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 12
rules:
  no-console: off
  radix: off
  semi: 2
  no-trailing-spaces: 2
  block-spacing: 2
