service: janelia-neuronbridge-cds

projectDir: ../

plugins:
  - serverless-appsync-plugin
  - serverless-bundle
  - serverless-deployment-bucket
  - serverless-step-functions

custom:
  version: 3.0.0
  tracing: false
  debug: true

  downloadBucket: ${file(../config.yml):config.downloadBucket}
  dataBucket: ${file(../config.yml):config.dataBucket}
  libraryBucket: ${file(../config.yml):config.libraryBucket}
  libraryThumbnailsBucket: ${file(../config.yml):config.libraryThumbnailsBucket}
  pppmBucket: ${file(../config.yml):config.pppmBucket}

  oldSearchTable: janelia-neuronbridge-search-table-prod
  oldSearchBucket: janelia-neuronbridge-searches-prod
  oldUserPoolId: us-east-1_owgI6RY6Y
  oldClientId: 4ham9v2s8c0d9v9mdm7vk3fggp

  searchBucket: ${file(../config.yml):config.searchBucket}
  searchTable: janelia-neuronbridge-${self:provider.stage}-search-table

  # Resources from burst-compute
  burstComputeStage: ${env:BURST_COMPUTE_STAGE, 'dev'}
  tasksTable: ${cf:burst-compute-${self:custom.burstComputeStage}.TasksTable}
  parallelDispatchFunction: ${cf:burst-compute-${self:custom.burstComputeStage}.DispatchLambdaFunction}
  searchBatchSize: 40
  searchParallelization: 10000
  cdsTimeoutInSeconds: 300

  # publishedNameTable uses a data version instead of prod or dev, so we have to map
  # the data version to the stage in use, using the mapping below.
  publishedNamesDb:
    dev: v2.3.0
    val: v2.2.0
    prod: v2.3.0
    int: v2.3.0

  # we shouldn't need backups on any stage apart from production.
  enableBackups:
    prod: true
    other: false

  publishedNamesTable: janelia-neuronbridge-published-${self:custom.publishedNamesDb.${self:provider.stage}}

  appSync:
    name: neuronbridge-appsync-${self:provider.stage}
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
      userPoolId:
       Ref: CognitoUserPool
    additionalAuthenticationProviders:
      - authenticationType: AWS_IAM
    schema: graphql/schema.graphql
    mappingTemplatesLocation: graphql/mapping-templates
    mappingTemplates:
      - dataSource: NeuronBridge_GraphQLDS_${self:provider.stage}
        type: Query
        field: getSearch
        request: "dynamodb-getSearch-request-template.vtl"
        response: "dynamodb-getSearch-response-template.vtl"
      - dataSource: NeuronBridge_GraphQLDS_${self:provider.stage}
        type: Query
        field: listSearches
        request: "dynamodb-listSearches-request-template.vtl"
        response: "dynamodb-listSearches-response-template.vtl"
      - dataSource: NeuronBridge_GraphQLDS_${self:provider.stage}
        type: Query
        field: listAllSearches
        request: "dynamodb-listAllSearches-request-template.vtl"
        response: "dynamodb-listAllSearches-response-template.vtl"
      - dataSource: NeuronBridge_GraphQLDS_${self:provider.stage}
        type: Mutation
        field: createSearch
        request: "dynamodb-createSearch-request-template.vtl"
        response: "dynamodb-createSearch-response-template.vtl"
      - dataSource: NeuronBridge_GraphQLDS_${self:provider.stage}
        type: Mutation
        field: deleteSearch
        request: "dynamodb-deleteSearch-request-template.vtl"
        response: "dynamodb-deleteSearch-response-template.vtl"
      - dataSource: NeuronBridge_GraphQLDS_${self:provider.stage}
        type: Mutation
        field: updateSearch
        request: "dynamodb-updateSearch-request-template.vtl"
        response: "dynamodb-updateSearch-response-template.vtl"
    dataSources:
      - type: AMAZON_DYNAMODB
        name: NeuronBridge_GraphQLDS_${self:provider.stage}
        description: Table containing neuron searches
        config:
          tableName: ${self:custom.searchTable}


provider:
  name: aws
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, "dev"}
  deploymentBucket:
    name: janelia-serverless-deployments
    blockPublicAccess: true
  tags:
    PROJECT: NeuronBridge
    VERSION: ${self:custom.version}
    DEVELOPER: ${env:USER}
  lambdaHashingVersion: 20201221
  stackTags:
    PROJECT: NeuronBridge
    VERSION: ${self:custom.version}
    DEVELOPER: ${env:USER}
    STAGE: ${self:provider.stage}
  tracing:
    lambda: ${self:custom.tracing}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:GetObjectTagging
            - s3:ListBucket
          Resource:
            - "arn:aws:s3:::${self:custom.libraryBucket}"
            - "arn:aws:s3:::${self:custom.libraryBucket}/*"
            - "arn:aws:s3:::${self:custom.libraryThumbnailsBucket}"
            - "arn:aws:s3:::${self:custom.libraryThumbnailsBucket}/*"
            - "arn:aws:s3:::${self:custom.searchBucket}"
            - "arn:aws:s3:::${self:custom.searchBucket}/*"
            - "arn:aws:s3:::${self:custom.downloadBucket}"
            - "arn:aws:s3:::${self:custom.downloadBucket}/*"
            - "arn:aws:s3:::${self:custom.oldSearchBucket}"
            - "arn:aws:s3:::${self:custom.oldSearchBucket}/*"
            - "arn:aws:s3:::${self:custom.dataBucket}"
            - "arn:aws:s3:::${self:custom.dataBucket}/*"
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectTagging
          Resource:
            - "arn:aws:s3:::${self:custom.searchBucket}/"
            - "arn:aws:s3:::${self:custom.searchBucket}/*"
            - "arn:aws:s3:::${self:custom.downloadBucket}"
            - "arn:aws:s3:::${self:custom.downloadBucket}/*"
        - Effect: Allow
          Action:
            - s3:DeleteObject
          Resource:
            - "arn:aws:s3:::${self:custom.searchBucket}/*"
            - "arn:aws:s3:::${self:custom.downloadBucket}/*"
        - Effect: "Allow"
          Action:
            - dynamodb:DescribeStream
            - dynamodb:DescribeTable
            - dynamodb:GetRecords
            - dynamodb:ListStreams
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:UpdateTable
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.searchTable}"
        - Effect: "Allow"
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tasksTable}"
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
            - lambda:InvokeAsync
          Resource: "*"
        - Effect: Allow
          Action:
            - states:StartExecution
          Resource: "*"
        - Effect: Allow
          Action:
            - appsync:GraphQL
          Resource: { Fn::Join: [
            "",
            [
              "arn:aws:appsync:",
              {
                Ref: "AWS::Region"
              },
              ":",
              {
                Ref: "AWS::AccountId"
              },
              ":apis/",
              {
                Fn::GetAtt: [ GraphQlApi, ApiId ]
              },
              "/*"
            ]
          ]}
        - Effect: Allow
          Action:
            - batch:DescribeJobs
            - batch:SubmitJob
          Resource: "*"
        - Effect: Allow
          Action:
            - cognito-idp:AdminGetUser
            - cognito-idp:ListUsers
          Resource:
            - { Fn::Join: [
              "",
              [
                "arn:aws:cognito-idp:",
                {
                  Ref: "AWS::Region"
                },
                ":*:userpool/",
                {
                  Ref: CognitoUserPool
                }
              ]
            ]}
            - "arn:aws:cognito-idp:${self:provider.region}:*:userpool/${self:custom.oldUserPoolId}"
        - Effect: Allow
          Action:
            - dynamodb:Scan
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.oldSearchTable}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.searchTable}"


  httpApi:
    useProviderTags: true
    payload: "2.0"
    cors: true
    authorizers:
      neuronBridgeJwtAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: { Fn::Join: [
          "",
          [
            "https://cognito-idp.",
            {
              Ref: "AWS::Region"
            },
            ".amazonaws.com/",
            {
              Ref: CognitoUserPool
            }
          ]
        ]}
        audience: !Ref CognitoUserPoolClient


package:
  individually: true
  patterns:
    - 'src/main/nodejs/**'


functions:

  appStarter:
    runtime: nodejs12.x
    handler: src/main/nodejs/app_starter.appStarter
    memorySize: 256
    timeout: 25
    maximumEventAge: 120
    maximumRetryAttempts: 1
    environment:
      ALIGN_JOB_STATE_MACHINE_ARN: !Ref JobMonitorStateMachine
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }
      BATCH_SIZE: ${self:custom.searchBatchSize}
      DEBUG: ${self:custom.debug}
      JOB_DEFINITION: ${file(../align/serverless.yml):service}-${self:provider.stage}-align-job-definition
      JOB_QUEUE: ${file(../align/serverless.yml):service}-${self:provider.stage}-align-job-queue-highpriority
      LIBRARY_BUCKET: ${self:custom.libraryBucket}
      MAX_ALIGNMENTS_PER_DAY: ${file(../config.yml):config.perDayAlignmentLimits}
      MAX_ALLOWED_CONCURRENT_ALIGNMENTS: ${file(../config.yml):config.concurrentAlignmentLimits}
      MAX_ALLOWED_CONCURRENT_SEARCHES: ${file(../config.yml):config.concurrentSearchLimits}
      MAX_PARALLELISM: ${self:custom.searchParallelization}
      MAX_SEARCHES_PER_DAY: ${file(../config.yml):config.perDaySearchLimits}
      PARALLEL_DISPATCH_FUNCTION_ARN: ${self:custom.parallelDispatchFunction}
      REDUCE_FUNCTION: !Ref CombinerLambdaFunction
      SEARCH_BUCKET: ${self:custom.searchBucket}
      SEARCH_FUNCTION: !Ref SearchLambdaFunction
      SEARCH_TIMEOUT_SECS: ${self:custom.cdsTimeoutInSeconds}
    events:
      - httpApi:
          method: POST
          path: /searches
          authorizer:
            name: neuronBridgeJwtAuthorizer

  cdsStarter:
    runtime: nodejs12.x
    handler: src/main/nodejs/cds_starter.cdsStarter
    memorySize: 256
    timeout: 25
    maximumEventAge: 120
    maximumRetryAttempts: 1
    environment:
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }
      BATCH_SIZE: ${self:custom.searchBatchSize}
      DEBUG: ${self:custom.debug}
      LIBRARY_BUCKET: ${self:custom.libraryBucket}
      MAX_PARALLELISM: ${self:custom.searchParallelization}
      PARALLEL_DISPATCH_FUNCTION_ARN: ${self:custom.parallelDispatchFunction}
      REDUCE_FUNCTION: !Ref CombinerLambdaFunction
      SEARCH_BUCKET: ${self:custom.searchBucket}
      SEARCH_FUNCTION: !Ref SearchLambdaFunction
      SEARCH_TIMEOUT_SECS: ${self:custom.cdsTimeoutInSeconds}

  combiner:
    runtime: nodejs12.x
    handler: src/main/nodejs/search_combiner.searchCombiner
    memorySize: 384
    timeout: ${self:custom.cdsTimeoutInSeconds}
    environment:
      DEBUG: ${self:custom.debug}
      SEARCH_BUCKET: ${self:custom.searchBucket}
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }

  monitor:
    runtime: nodejs12.x
    handler: src/main/nodejs/monitor.isJobDone
    memorySize: 128
    timeout: 180
    environment:
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }
      DEBUG: ${self:custom.debug}

  search:
    runtime: nodejs12.x
    handler: src/main/nodejs/batch_search.batchSearch
    memorySize: 256
    timeout: ${self:custom.cdsTimeoutInSeconds}
    environment:
      DEBUG: ${self:custom.debug}
      SEARCHED_IMAGES_BUCKET: ${self:custom.libraryBucket}
      SEARCHED_THUMBNAILS_BUCKET: ${self:custom.libraryThumbnailsBucket}

  searchJava:
    package:
      artifact: target/neuronbridge-search-${self:custom.version}.jar
    runtime: java8
    handler: org.janelia.colordepthsearch.BatchSearch
    memorySize: 384
    timeout: ${self:custom.cdsTimeoutInSeconds}
    environment:
      DEBUG: ${self:custom.debug}
      SEARCHED_IMAGES_BUCKET: ${self:custom.libraryBucket}
      SEARCHED_THUMBNAILS_BUCKET: ${self:custom.libraryThumbnailsBucket}

  searchCopyAlignment:
    runtime: nodejs12.x
    handler: src/main/nodejs/search_copy.searchCopyAlignment
    memorySize: 128
    timeout: 10
    maximumEventAge: 120
    maximumRetryAttempts: 1
    environment:
      DEBUG: ${self:custom.debug}
      SEARCH_BUCKET: ${self:custom.searchBucket}
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }
    events:
      - httpApi:
          method: POST
          path: /copy_alignment
          authorizer:
            name: neuronBridgeJwtAuthorizer

  searchCreateDefaultChannel:
    runtime: nodejs12.x
    handler: src/main/nodejs/search_create_default_channel.searchCreateDefaultChannel
    memorySize: 128
    timeout: 10
    maximumEventAge: 120
    maximumRetryAttempts: 1
    environment:
      DEBUG: ${self:custom.debug}
      SEARCH_BUCKET: ${self:custom.searchBucket}
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }
    events:
      - httpApi:
          method: POST
          path: /create_default_channel
          authorizer:
            name: neuronBridgeJwtAuthorizer

  searchNewFromImage:
    runtime: nodejs12.x
    handler: src/main/nodejs/search_new_from_image.searchNewFromImage
    memorySize: 128
    timeout: 10
    maximumEventAge: 120
    maximumRetryAttempts: 1
    environment:
      DEBUG: ${self:custom.debug}
      SEARCH_BUCKET: ${self:custom.searchBucket}
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }
    events:
      - httpApi:
          method: POST
          path: /new_from_image
          authorizer:
            name: neuronBridgeJwtAuthorizer

  searchUpdate:
    runtime: nodejs12.x
    handler: src/main/nodejs/search_update.searchUpdate
    memorySize: 128
    timeout: 25
    environment:
      DEBUG: ${self:custom.debug}
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }

  downloadCreator:
    runtime: nodejs12.x
    handler: src/main/nodejs/download_creator.downloadCreator
    memorySize: 256
    timeout: 200
    # maximum timeout for an http API gateway is 29 seconds, so this
    # could bite us. Might have to resort to triggering a lambda and
    # then have the site poll for results against the dynamoDB.
    maximumEventAge: 60
    maximumRetryAttempts: 1
    environment:
      DEBUG: ${self:custom.debug}
      SEARCH_BUCKET: ${self:custom.searchBucket}
      DOWNLOAD_BUCKET: ${self:custom.downloadBucket}
      DATA_BUCKET: ${self:custom.dataBucket}
      LIBRARY_BUCKET: ${self:custom.libraryBucket}
      PPP_BUCKET: ${self:custom.pppmBucket}
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }
      IDENTITY_POOL_ID: !Ref CognitoUserPoolClient
    events:
      - httpApi:
          method: POST
          path: /create_download
          authorizer:
            name: neuronBridgeJwtAuthorizer

  dataMigration:
    runtime: nodejs14.x
    handler: src/main/nodejs/data_migration.dataMigration
    role: dataMigrationRole
    memorySize: 128
    timeout: 28
    # maximum timeout for an http API gateway is 29 seconds, so this
    # could bite us. Might have to resort to triggering a lambda and
    # then have the site poll for results against the dynamoDB.
    maximumEventAge: 60
    maximumRetryAttempts: 1
    environment:
      DEBUG: ${self:custom.debug}
      SEARCH_BUCKET: ${self:custom.searchBucket}
      DOWNLOAD_BUCKET: ${self:custom.downloadBucket}
      DATA_BUCKET: ${self:custom.dataBucket}
      LIBRARY_BUCKET: ${self:custom.libraryBucket}
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }
      IDENTITY_POOL_ID: !Ref CognitoUserPoolClient
      SEARCH_TABLE: ${self:custom.searchTable}
      USERPOOL_ID:
        Ref: CognitoUserPool
      OLD_SEARCH_TABLE: ${self:custom.oldSearchTable}
      OLD_SEARCH_BUCKET: ${self:custom.oldSearchBucket}
      OLD_USERPOOL_ID: ${self:custom.oldUserPoolId}
    events:
      - httpApi:
          method: POST
          path: /migrate_data
          authorizer:
            name: neuronBridgeJwtAuthorizer

  migrationCheck:
    runtime: nodejs14.x
    handler: src/main/nodejs/migration_check.migrationCheck
    memorySize: 128
    timeout: 28
    # maximum timeout for an http API gateway is 29 seconds, so this
    # could bite us. Might have to resort to triggering a lambda and
    # then have the site poll for results against the dynamoDB.
    maximumEventAge: 60
    maximumRetryAttempts: 1
    environment:
      DEBUG: ${self:custom.debug}
      SEARCH_BUCKET: ${self:custom.searchBucket}
      DOWNLOAD_BUCKET: ${self:custom.downloadBucket}
      DATA_BUCKET: ${self:custom.dataBucket}
      LIBRARY_BUCKET: ${self:custom.libraryBucket}
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }
      IDENTITY_POOL_ID: !Ref CognitoUserPoolClient
      SEARCH_TABLE: ${self:custom.searchTable}
      USERPOOL_ID:
        Ref: CognitoUserPool
      OLD_SEARCH_TABLE: ${self:custom.oldSearchTable}
      OLD_SEARCH_BUCKET: ${self:custom.oldSearchBucket}
      OLD_USERPOOL_ID: ${self:custom.oldUserPoolId}
    events:
      - httpApi:
          method: GET
          path: /migration_check
          authorizer:
            name: neuronBridgeJwtAuthorizer

  userMigration:
    runtime: nodejs14.x
    handler: src/main/nodejs/user_migration_lamda.userMigration
    role: userMigrationRole
    memorySize: 128
    maximumEventAge: 60
    maximumRetryAttempts: 1
    environment:
      OLD_USER_POOL_ID: ${self:custom.oldUserPoolId}
      OLD_CLIENT_ID: ${self:custom.oldClientId}
    events:
      - cognitoUserPool:
          pool: CognitoUserPool
          trigger: UserMigration

  publishedNames:
    runtime: nodejs14.x
    timeout: 10
    role: publishedNames
    handler: src/main/nodejs/published_names.publishedNames
    environment:
      DEBUG: ${self:custom.debug}
      NAMES_TABLE: ${self:custom.publishedNamesTable}
      ITEM_LIMIT: 100
    events:
      - httpApi:
          method: GET
          path: /published_names
          authorizer:
            name: neuronBridgeJwtAuthorizer

stepFunctions:
  validate: true # enable pre-deployment definition validation
  stateMachines:
    jobMonitorStateMachine:
      id: JobMonitorStateMachine
      name: jobMonitorStateMachine-${self:service}-${self:provider.stage}
      definition:
        StartAt: Monitor
        States:
          Monitor:
            Type: Task
            Resource:
              Fn::GetAtt: [monitor, Arn]
            Retry:
              - ErrorEquals:
                  - Lambda.TooManyRequestsException
                IntervalSeconds: 1
                MaxAttempts: 100
            Next: AreWeDoneYet
          AreWeDoneYet:
            Type: Choice
            Choices:
              - Variable: "$.completed"
                BooleanEquals: true
                Next: CheckErrors
            Default: Wait
          Wait:
            Type: Wait
            Seconds: 300
            Next: Monitor
          CheckErrors:
            Type: Choice
            Choices:
              - Variable: "$.withErrors"
                BooleanEquals: true
                Next: ErrorState
            Default: EndState
          ErrorState:
            Type: Fail
            Cause: "Job completed with errors"
          EndState:
            Type: Pass
            End: true

resources:
  - ${file(sls_resources/cognito-pools.yml)}
  - ${file(sls_resources/buckets.yml)}
  - ${file(sls_resources/outputs.yml)}
  - ${file(sls_resources/dynamodb.yml)}
  - ${file(sls_resources/iam_roles.yml)}
