service: janelia-neuronbridge-services


plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-appsync-plugin


custom:
  libraryBucket: janelia-flylight-color-depth-dev
  libraryThumbnailsBucket: janelia-flylight-color-depth-thumbnails-dev
  alignmentTemplatesBucket: janelia-flylight-color-depth-dev
  alignmentTemplatesFolder: alignment_templates
  searchBucket: janelia-neuronbridge-searches-dev
  searchTable: janelia-neuronbridge-search-table-${self:provider.stage}
  cognitoUserPoolId: us-east-1_owgI6RY6Y
  neuronbridgeAppId: 4ham9v2s8c0d9v9mdm7vk3fggp
  cdsTimeoutInSeconds: 300
  version: 2.0.0
  tracing: true
  debug: true
  securityGroupId: sg-963ee8df
  subnetId: subnet-5e11c814
  ec2AlignmentImageId: ami-0d3f5e4624981ef1b
  alignmentContainerImage: cgoina/neuronbridge-aligner:1.0
  defaultAlignmentThreads: 8
  sshKeyPairName: ec2_batch
  appSync:
    name: neuronbridge-appsync-${self:provider.stage}
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
      userPoolId: ${self:custom.cognitoUserPoolId}
    additionalAuthenticationProviders:
      - authenticationType: AWS_IAM
    schema: graphql/schema.graphql
    mappingTemplatesLocation: graphql/mapping-templates
    mappingTemplates:
      - dataSource: NeuronBridge_GraphQLDS_${self:provider.stage}
        type: Query
        field: getSearch
        request: "dynamodb-getSearch-request-template.vtl"
        response: "dynamodb-getSearch-response-template.vtl"
      - dataSource: NeuronBridge_GraphQLDS_${self:provider.stage}
        type: Query
        field: listSearches
        request: "dynamodb-listSearches-request-template.vtl"
        response: "dynamodb-listSearches-response-template.vtl"
      - dataSource: NeuronBridge_GraphQLDS_${self:provider.stage}
        type: Mutation
        field: createSearch
        request: "dynamodb-createSearch-request-template.vtl"
        response: "dynamodb-createSearch-response-template.vtl"
      - dataSource: NeuronBridge_GraphQLDS_${self:provider.stage}
        type: Mutation
        field: deleteSearch
        request: "dynamodb-deleteSearch-request-template.vtl"
        response: "dynamodb-deleteSearch-response-template.vtl"
      - dataSource: NeuronBridge_GraphQLDS_${self:provider.stage}
        type: Mutation
        field: updateSearch
        request: "dynamodb-updateSearch-request-template.vtl"
        response: "dynamodb-updateSearch-response-template.vtl"
    dataSources:
      - type: AMAZON_DYNAMODB
        name: NeuronBridge_GraphQLDS_${self:provider.stage}
        description: Table containing neuron searches
        config:
          tableName: ${self:custom.searchTable}


provider:
  name: aws
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, "cgdev"}
  tags:
    PROJECT: NeuronBridge
    VERSION: ${self:custom.version}
    DEVELOPER: ${env:USER}
  stackTags:
    PROJECT: NeuronBridge
    VERSION: ${self:custom.version}
    DEVELOPER: ${env:USER}
  tracing:
    lambda: ${self:custom.tracing}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:ListBucket
      Resource:
        - "arn:aws:s3:::${self:custom.libraryBucket}"
        - "arn:aws:s3:::${self:custom.libraryBucket}/*"
        - "arn:aws:s3:::${self:custom.searchBucket}"
        - "arn:aws:s3:::${self:custom.searchBucket}/*"
        - "arn:aws:s3:::${self:custom.alignmentTemplatesBucket}"
        - "arn:aws:s3:::${self:custom.alignmentTemplatesBucket}/*"
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::${self:custom.searchBucket}/"
        - "arn:aws:s3:::${self:custom.searchBucket}/*"
    - Effect: Allow
      Action:
        - s3:DeleteObject
      Resource:
        - "arn:aws:s3:::${self:custom.searchBucket}/*"
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.searchTable}"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
    - Effect: Allow
      Action:
        - states:StartExecution
      Resource: "*"
    - Effect: Allow
      Action:
        - appsync:GraphQL
      Resource: { Fn::Join: [
        "",
        [
          "arn:aws:appsync:",
          {
            Ref: "AWS::Region"
          },
          ":",
          {
            Ref: "AWS::AccountId"
          },
          ":apis/",
          {
            Fn::GetAtt: [ GraphQlApi, ApiId ]
          },
          "/*"
        ]
      ]}
    - Effect: Allow
      Action:
        - batch:SubmitJob
      Resource: "arn:aws:batch:*:*:*"
  httpApi:
    payload: "2.0"
    cors: true
    authorizers:
      neuronBridgeJwtAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${self:custom.cognitoUserPoolId}
        audience:
          - ${self:custom.neuronbridgeAppId}


package:
  individually: true
  exclude:
    - pom.xml
    - ./*.iml
    - .idea/**
    - target/**
    - src/test/**
    - src/main/java/**
    - src/main/resources/**
  include:
    - src/main/nodejs/**


functions:

  denormalize:
    runtime: nodejs12.x
    handler: src/main/nodejs/denormalize.denormalize
    memorySize: 128
    timeout: 900

  searchStarter:
    runtime: nodejs12.x
    handler: src/main/nodejs/search_starter.searchStarter
    memorySize: 256
    timeout: 25
    environment:
      DEBUG: ${self:custom.debug}
      SEARCH_DISPATCH_FUNCTION: ${self:service}-${self:provider.stage}-searchDispatch
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }
      JOB_DEFINITION: !Select [ 1, !Split [ /, !Ref ComputeAlignmentJobDefinition ] ]
      JOB_QUEUE: !Select [ 1, !Split [ /, !Ref ComputeAlignmentJobQueue ] ]
    events:
      - httpApi:
          method: POST
          path: /searches
          cors: true
          authorizer:
            name: neuronBridgeJwtAuthorizer
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - SearchTable
              - StreamArn
          batchSize: 1

  searchDispatch:
    runtime: nodejs12.x
    handler: src/main/nodejs/search_dispatch.searchDispatch
    memorySize: 256
    # 5 minute timeout
    timeout: 300
    environment:
      LIBRARY_BUCKET: ${self:custom.libraryBucket}
      SEARCH_BUCKET: ${self:custom.searchBucket}
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }
      SEARCH_DISPATCH_FUNCTION: ${self:service}-${self:provider.stage}-searchDispatch
      SEARCH_FUNCTION: ${self:service}-${self:provider.stage}-search
      STATE_MACHINE_ARN: ${self:resources.Outputs.SearchMonitorStateMachine.Value}
      DEBUG: ${self:custom.debug}

  search:
    package:
      artifact: target/neuronbridge-search-${self:custom.version}.jar
    runtime: java8
    handler: org.janelia.colordepthsearch.BatchSearch
    memorySize: 256
    # 5 minute timeout
    timeout: 300
    environment:
      SEARCHED_IMAGES_BUCKET: ${self:custom.libraryBucket}
      SEARCHED_THUMBNAILS_BUCKET: ${self:custom.libraryThumbnailsBucket}

  monitor:
    runtime: nodejs12.x
    handler: src/main/nodejs/monitor.isSearchDone
    memorySize: 128
    # 5 minute timeout because the last iteration also runs the reduce step
    timeout: 300
    environment:
      SEARCH_TIMEOUT_SECS: ${self:custom.cdsTimeoutInSeconds}
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }
      DEBUG: ${self:custom.debug}

  searchReduce:
    runtime: nodejs12.x
    handler: src/main/nodejs/search_reducer.searchReducer
    memorySize: 256
    # 5 minute timeout
    timeout: 300
    environment:
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
      SEARCH_BUCKET: ${self:custom.searchBucket}
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }
      DEBUG: ${self:custom.debug}

  searchUpdate:
    runtime: nodejs12.x
    handler: src/main/nodejs/search_update.searchUpdate
    memorySize: 128
    timeout: 25
    environment:
      DEBUG: ${self:custom.debug}
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }

  em2lmGradScorer:
    package:
      artifact: target/neuronbridge-search-${self:custom.version}.jar
    runtime: java8
    handler: org.janelia.colordepthsearch.AWSLambdaEM2LMGradientScoreCalc
    memorySize: 256
    # 5 minute timeout
    timeout: 300


stepFunctions:

  stateMachines:
    searchMonitorStateMachine:
      id: SearchMonitorStateMachine
      name: searchMonitorStateMachine-${self:service}-${self:provider.stage}
      definition:
        Comment: "Monitors a parallel Color Depth Search and notifies the user upon completion"
        StartAt: Monitor
        States:
          Monitor:
            Type: Task
            Resource:
              Fn::GetAtt: [monitor, Arn]
            Retry:
              - ErrorEquals: 
                - Lambda.TooManyRequestsException
                IntervalSeconds: 1
                MaxAttempts: 100
            Next: IsTimedOut
          IsTimedOut:
            Type: Choice
            Choices:
              - Variable: "$.timedOut"
                BooleanEquals: true
                Next: TimedOut
            Default: AreWeDoneYet
          AreWeDoneYet:
            Type: Choice
            Choices:
              - Variable: "$.completed"
                BooleanEquals: true
                Next: Reduce
            Default: Wait
          Wait:
            Type: Wait
            Seconds: 30
            Next: Monitor
          TimedOut:
            Type: Fail
            Cause: "Search timed out"
          Reduce:
            Type: Task
            Resource:
              Fn::GetAtt: [searchReduce, Arn]
            Next: EndState
          EndState:
            Type: Pass
            End: true

  validate: true # enable pre-deployment definition validation


resources:

  Outputs:
    SearchMonitorStateMachine:
      Description: The ARN of the state machine
      Value:
        Ref: SearchMonitorStateMachine

  Resources:
    SearchTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: KEYS_ONLY
        TableName: ${self:custom.searchTable}

    ComputeAlignmentSpotEnv:
      Type: AWS::Batch::ComputeEnvironment
      Properties:
        Type: MANAGED
        State: ENABLED
        ServiceRole: !Ref BatchServiceRole
        ComputeEnvironmentName: "#{AWS::StackName}-compute-alignment"
        ComputeResources:
          Type: SPOT
          BidPercentage: 50
          AllocationStrategy: BEST_FIT_PROGRESSIVE
          MinvCpus: 0
          DesiredvCpus: 0
          MaxvCpus: 64
          InstanceTypes:
            - optimal
          ImageId: ${self:custom.ec2AlignmentImageId}
          Subnets:
            - ${self:custom.subnetId}
          SecurityGroupIds:
            - ${self:custom.securityGroupId}
          Ec2KeyPair: ${self:custom.sshKeyPairName}
          SpotIamFleetRole: !Ref SpotFleetRole
          InstanceRole: ecsInstanceRole
          Tags: ${self:provider.tags}

    ComputeAlignmentJobQueue:
      Type: AWS::Batch::JobQueue
      Properties:
        ComputeEnvironmentOrder:
          - Order: 0
            ComputeEnvironment: !Ref ComputeAlignmentSpotEnv
        State: ENABLED
        Priority: 100
        JobQueueName: "#{AWS::StackName}-align-spot"

    ComputeAlignmentJobDefinition:
      Type: "AWS::Batch::JobDefinition"
      Properties:
        JobDefinitionName: "#{AWS::StackName}-alignment-job"
        Type: Container
        RetryStrategy:
          Attempts: 1
        Timeout:
          AttemptDurationSeconds: 7200
        Parameters:
          iam_role: auto
          debug_flag: ${self:custom.debug}
          templates_bucket: ${self:custom.alignmentTemplatesBucket}
          inputs_bucket: ${self:custom.searchBucket}
          outputs_bucket: ${self:custom.searchBucket}
          templates_dir: ${self:custom.alignmentTemplatesFolder}
          xy_resolution: ""
          z_resolution: ""
          nchannels: 2
          force_voxel_size: false
          nslots: ${self:custom.defaultAlignmentThreads}
        ContainerProperties:
          Image: ${self:custom.alignmentContainerImage}
          Vcpus: 8
          Memory: 8192
          JobRoleArn: !Ref ECSTaskRole
          Command:
            - /opt/aligner-scripts/run_aligner_using_aws.sh
            - "-debug"
            - "Ref::debug_flag"
            - "--use-iam-role"
            - "Ref::iam_role"
            - "--templates-s3bucket-name"
            - "Ref::templates_bucket"
            - "--inputs-s3bucket-name"
            - "Ref::inputs_bucket"
            - "--outputs-s3bucket-name"
            - "Ref::outputs_bucket"
            - "--templatedir"
            - "Ref::templates_dir"
            - "--xyres"
            - "Ref::xy_resolution"
            - "--zres"
            - "Ref::z_resolution"
            - "--nchannels"
            - "Ref::nchannels"
            - "--forceVxSize"
            - "Ref::force_voxel_size"
            - "--nslots"
            - "Ref::nslots"
            - "--search-id"
            - "Ref::search_id"
            - "-i"
            - "Ref::input_filename"
            - "-o"
            - "Ref::output_folder"
          Volumes:
            - Name: scratch_data_volume
              Host:
                SourcePath: /scratch_volume/data
            - Name: scratch_tmp_volume
              Host:
                SourcePath: /scratch_volume/tmp
          MountPoints:
            - ContainerPath: /scratch
              ReadOnly: false
              SourceVolume: scratch_data_volume
            - ContainerPath: /tmp
              ReadOnly: false
              SourceVolume: scratch_tmp_volume
          Environment:
            - Name: FB_MODE
              Value: xvfb
            - Name: SEARCH_UPDATE_FUNCTION
              Value: ${self:service}-${self:provider.stage}-searchUpdate
          ReadonlyRootFilesystem: true
          Privileged: true
          LinuxParameters:
            Devices:
              - HostPath: /dev/fuse
                ContainerPath: ""
                Permissions:
                  - READ
                  - WRITE
                  - MKNOD

    BatchServiceRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - "batch.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole"
          - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        Policies:
          - PolicyName: AWSLambdaInvokeAccess
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                    - lambda:InvokeAsync
                  Resource: '*'
              Version: '2012-10-17'

    ECSTaskRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - "ecs-tasks.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
          - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"

    SpotFleetRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - "spotfleet.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole"
