service: janelia-neuronbridge-cds


plugins:
  - serverless-step-functions
  - serverless-appsync-plugin
custom:
  libraryBucket: ${file(../config.yml):config.libraryBucket}
  libraryThumbnailsBucket: ${file(../config.yml):config.libraryThumbnailsBucket}
  searchBucket: ${file(../config.yml):config.searchBucket}
  searchTable: janelia-neuronbridge-search-table-${self:provider.stage}
  # Resources from burst-compute
  burstComputeStage: dev
  tasksTable: ${cf:burst-compute-${self:custom.burstComputeStage}.TasksTable}
  dispatchFunction: ${cf:burst-compute-${self:custom.burstComputeStage}.DispatchLambdaFunction}

  searchBatchSize: 40
  searchParallelization: 10000
  cognitoUserPoolId: us-east-1_owgI6RY6Y
  neuronbridgeAppId: 4ham9v2s8c0d9v9mdm7vk3fggp
  cdsTimeoutInSeconds: 300
  version: 3.0.0
  tracing: false
  debug: true
  appSync:
    name: neuronbridge-appsync-${self:provider.stage}
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
      userPoolId: ${self:custom.cognitoUserPoolId}
    additionalAuthenticationProviders:
      - authenticationType: AWS_IAM
    schema: graphql/schema.graphql
    mappingTemplatesLocation: graphql/mapping-templates
    mappingTemplates:
      - dataSource: NeuronBridge_GraphQLDS_${self:provider.stage}
        type: Query
        field: getSearch
        request: "dynamodb-getSearch-request-template.vtl"
        response: "dynamodb-getSearch-response-template.vtl"
      - dataSource: NeuronBridge_GraphQLDS_${self:provider.stage}
        type: Query
        field: listSearches
        request: "dynamodb-listSearches-request-template.vtl"
        response: "dynamodb-listSearches-response-template.vtl"
      - dataSource: NeuronBridge_GraphQLDS_${self:provider.stage}
        type: Query
        field: listAllSearches
        request: "dynamodb-listAllSearches-request-template.vtl"
        response: "dynamodb-listAllSearches-response-template.vtl"
      - dataSource: NeuronBridge_GraphQLDS_${self:provider.stage}
        type: Mutation
        field: createSearch
        request: "dynamodb-createSearch-request-template.vtl"
        response: "dynamodb-createSearch-response-template.vtl"
      - dataSource: NeuronBridge_GraphQLDS_${self:provider.stage}
        type: Mutation
        field: deleteSearch
        request: "dynamodb-deleteSearch-request-template.vtl"
        response: "dynamodb-deleteSearch-response-template.vtl"
      - dataSource: NeuronBridge_GraphQLDS_${self:provider.stage}
        type: Mutation
        field: updateSearch
        request: "dynamodb-updateSearch-request-template.vtl"
        response: "dynamodb-updateSearch-response-template.vtl"
    dataSources:
      - type: AMAZON_DYNAMODB
        name: NeuronBridge_GraphQLDS_${self:provider.stage}
        description: Table containing neuron searches
        config:
          tableName: ${self:custom.searchTable}


provider:
  name: aws
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, "dev"}
  tags:
    PROJECT: NeuronBridge
    VERSION: ${self:custom.version}
    DEVELOPER: ${env:USER}
  stackTags:
    PROJECT: NeuronBridge
    VERSION: ${self:custom.version}
    DEVELOPER: ${env:USER}
    STAGE: ${self:provider.stage}
  tracing:
    lambda: ${self:custom.tracing}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
    DISABLE_XRAY: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:ListBucket
      Resource:
        - "arn:aws:s3:::${self:custom.libraryBucket}"
        - "arn:aws:s3:::${self:custom.libraryBucket}/*"
        - "arn:aws:s3:::${self:custom.searchBucket}"
        - "arn:aws:s3:::${self:custom.searchBucket}/*"
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::${self:custom.searchBucket}/"
        - "arn:aws:s3:::${self:custom.searchBucket}/*"
    - Effect: Allow
      Action:
        - s3:DeleteObject
      Resource:
        - "arn:aws:s3:::${self:custom.searchBucket}/*"
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeStream
        - dynamodb:DescribeTable
        - dynamodb:GetRecords
        - dynamodb:ListStreams
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:UpdateTable
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.searchTable}"
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tasksTable}"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
    - Effect: Allow
      Action:
        - states:StartExecution
      Resource: "*"
    - Effect: Allow
      Action:
        - appsync:GraphQL
      Resource: { Fn::Join: [
        "",
        [
          "arn:aws:appsync:",
          {
            Ref: "AWS::Region"
          },
          ":",
          {
            Ref: "AWS::AccountId"
          },
          ":apis/",
          {
            Fn::GetAtt: [ GraphQlApi, ApiId ]
          },
          "/*"
        ]
      ]}
    - Effect: Allow
      Action:
        - batch:DescribeJobs
        - batch:SubmitJob
      Resource: "*"
  httpApi:
    payload: "2.0"
    cors: true
    authorizers:
      neuronBridgeJwtAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${self:custom.cognitoUserPoolId}
        audience:
          - ${self:custom.neuronbridgeAppId}


package:
  individually: true
  exclude:
    - pom.xml
    - ./*.iml
    - .idea/**
    - target/**
    - src/test/**
    - src/main/java/**
    - src/main/resources/**
  include:
    - src/main/nodejs/**


functions:

  denormalize:
    runtime: nodejs12.x
    handler: src/main/nodejs/denormalize.denormalize
    memorySize: 128
    timeout: 900

  searchStarter:
    runtime: nodejs12.x
    handler: src/main/nodejs/search_starter.searchStarter
    memorySize: 256
    timeout: 25
    maximumEventAge: 120
    maximumRetryAttempts: 1
    environment:
      DEBUG: ${self:custom.debug}
      LIBRARY_BUCKET: ${self:custom.libraryBucket}
      SEARCH_BUCKET: ${self:custom.searchBucket}
      DISPATCH_FUNCTION_ARN: ${self:custom.dispatchFunction}
      SEARCH_FUNCTION: ${self:resources.Outputs.SearchLambdaFunction.Value}
      REDUCE_FUNCTION: ${self:resources.Outputs.CombinerLambdaFunction.Value}
      SEARCH_TIMEOUT_SECS: ${self:custom.cdsTimeoutInSeconds}
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }
      JOB_DEFINITION: ${file(../align/serverless.yml):service}-${self:provider.stage}-align-job-definition
      JOB_QUEUE: ${file(../align/serverless.yml):service}-${self:provider.stage}-align-job-queue-highpriority
      BATCH_SIZE: ${self:custom.searchBatchSize}
      MAX_PARALLELISM: ${self:custom.searchParallelization}
      MAX_SEARCHES_PER_DAY: ${file(../config.yml):config.perDaySearchLimits}
      MAX_ALLOWED_CONCURRENT_SEARCHES: ${file(../config.yml):config.concurrentSearchLimits}
      MAX_ALIGNMENTS_PER_DAY: ${file(../config.yml):config.perDayAlignmentLimits}
      MAX_ALLOWED_CONCURRENT_ALIGNMENTS: ${file(../config.yml):config.concurrentAlignmentLimits}
      ALIGN_JOB_STATE_MACHINE_ARN: ${self:resources.Outputs.JobMonitorStateMachine.Value}
    events:
      - httpApi:
          method: POST
          path: /searches
          authorizer:
            name: neuronBridgeJwtAuthorizer

  search-java:
    package:
      artifact: target/neuronbridge-search-${self:custom.version}.jar
    runtime: java8
    handler: org.janelia.colordepthsearch.BatchSearch
    memorySize: 384
    timeout: ${self:custom.cdsTimeoutInSeconds}
    environment:
      DEBUG: ${self:custom.debug}
      SEARCHED_IMAGES_BUCKET: ${self:custom.libraryBucket}
      SEARCHED_THUMBNAILS_BUCKET: ${self:custom.libraryThumbnailsBucket}

  search:
    runtime: nodejs12.x
    handler: src/main/nodejs/batch_search.batchSearch
    memorySize: 256
    # 5 minute timeout
    timeout: 300
    environment:
      DEBUG: ${self:custom.debug}
      SEARCHED_IMAGES_BUCKET: ${self:custom.libraryBucket}
      SEARCHED_THUMBNAILS_BUCKET: ${self:custom.libraryThumbnailsBucket}

  combiner:
    runtime: nodejs12.x
    handler: src/main/nodejs/search_combiner.searchCombiner
    memorySize: 384
    timeout: ${self:custom.cdsTimeoutInSeconds}
    environment:
      DEBUG: ${self:custom.debug}
      SEARCH_BUCKET: ${self:custom.searchBucket}
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }

  searchCopy:
    runtime: nodejs12.x
    handler: src/main/nodejs/search_copy.searchCopy
    memorySize: 128
    timeout: 10
    maximumEventAge: 120
    maximumRetryAttempts: 1
    environment:
      DEBUG: ${self:custom.debug}
      SEARCH_BUCKET: ${self:custom.searchBucket}
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }
    events:
      - httpApi:
          method: POST
          path: /copy
          authorizer:
            name: neuronBridgeJwtAuthorizer

  searchUpdate:
    runtime: nodejs12.x
    handler: src/main/nodejs/search_update.searchUpdate
    memorySize: 128
    timeout: 25
    environment:
      DEBUG: ${self:custom.debug}
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }

  monitor:
    runtime: nodejs12.x
    handler: src/main/nodejs/monitor.isSearchDone
    memorySize: 128
    timeout: 180
    environment:
      SEARCH_TIMEOUT_SECS: ${self:custom.cdsTimeoutInSeconds}
      APPSYNC_API_URL: { Fn::GetAtt: [ GraphQlApi, GraphQLUrl ] }
      DEBUG: ${self:custom.debug}

  em2lmGradScorer:
    package:
      artifact: target/neuronbridge-search-${self:custom.version}.jar
    runtime: java8
    handler: org.janelia.colordepthsearch.AWSLambdaEM2LMGradientScoreCalc
    memorySize: 256
    # 5 minute timeout
    timeout: 300

stepFunctions:
  validate: true # enable pre-deployment definition validation
  stateMachines:
    jobMonitorStateMachine:
      id: JobMonitorStateMachine
      name: jobMonitorStateMachine-${self:service}-${self:provider.stage}
      definition:
        StartAt: Monitor
        States:
          Monitor:
            Type: Task
            Resource:
              Fn::GetAtt: [monitor, Arn]
            Retry:
              - ErrorEquals:
                  - Lambda.TooManyRequestsException
                IntervalSeconds: 1
                MaxAttempts: 100
            Next: AreWeDoneYet
          AreWeDoneYet:
            Type: Choice
            Choices:
              - Variable: "$.completed"
                BooleanEquals: true
                Next: CheckErrors
            Default: Wait
          Wait:
            Type: Wait
            Seconds: 300
            Next: Monitor
          CheckErrors:
            Type: Choice
            Choices:
              - Variable: "$.withErrors"
                BooleanEquals: true
                Next: ErrorState
            Default: EndState
          ErrorState:
            Type: Fail
            Cause: "Job completed with errors"
          EndState:
            Type: Pass
            End: true

resources:
  Outputs:
    SearchLambdaFunction:
      Description: The ARN of the search function
      Value:
        Ref: SearchLambdaFunction
    MonitorLambdaFunction:
      Description: The ARN of the monitor function
      Value:
        Ref: MonitorLambdaFunction
    CombinerLambdaFunction:
      Description: The ARN of the combiner function
      Value:
        Ref: CombinerLambdaFunction
    JobMonitorStateMachine:
      Description: The ARN of the jobMonitorStateMachine 
      Value:
        Ref: JobMonitorStateMachine

  Resources:
    SearchTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.searchTable}

