service: neuronbridge-search

custom:
  maskBucket: color-depth-masks
  libraryBucket: color-depth-libraries
  searchBucket: color-depth-searches
  version: 0.0.1
  tracing: false

provider:
  name: aws
  region: us-east-1
  stage: dev
  tags:
    PROJECT: NeuronBridge
    DEVELOPER: ${env:USER}
    VERSION: ${self:custom.version}
  tracing:
    lambda: ${self:custom.tracing}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:ListBucket
      Resource:
        - "arn:aws:s3:::${self:custom.maskBucket}/*"
        - "arn:aws:s3:::${self:custom.libraryBucket}"
        - "arn:aws:s3:::${self:custom.libraryBucket}/*"
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::${self:custom.searchBucket}/*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

package:
  individually: true

functions:

  parallelSearch:
    package:
      artifact: target/neuronbridge-search.jar
    runtime: java8
    handler: org.janelia.colordepthsearch.ParallelSearch
    memorySize: 512
    # 5 minute timeout
    timeout: 300
    environment:
      MASK_BUCKET: ${self:custom.maskBucket}
      LIBRARY_BUCKET: ${self:custom.libraryBucket}
      SEARCH_BUCKET: ${self:custom.searchBucket}
      SEARCH_FUNCTION: ${self:service}-${self:provider.stage}-search

  search:
    package:
      artifact: target/neuronbridge-search.jar
    runtime: java8
    handler: org.janelia.colordepthsearch.BatchSearch
    memorySize: 512
    # 5 minute timeout
    timeout: 300

#resources:
#
#  Resources:
#    S3BucketInputs:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: ${self:custom.maskBucket}
#
#    S3BucketOutputs:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: ${self:custom.libraryBucket}
#
#    S3BucketSearches:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: ${self:custom.searchBucket}

