version: 2
jobs:
  build:

    branches:
      only:
       - master
   
    working_directory: ~/neuronbridge-services

    docker:
      - image: circleci/openjdk:8u171-jdk

    environment:
      TERM: dumb

    steps:

      - checkout

      - restore_cache:
          keys: 
            - neuronbridge-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - neuronbridge
      
      - run: mvn clean install -f search/pom.xml
      
      - save_cache:
          key: neuronbridge-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run: mvn package -f search/pom.xml

