version: 2

jobs:
  build-search-java:
    working_directory: ~/neuronbridge-services/search

    docker:
      - image: cimg/openjdk:8.0.345

    environment:
      TERM: dumb

    steps:
      - checkout:
          path: ~/neuronbridge-services

      - restore_cache:
          keys: 
            - neuronbridge-java-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - neuronbridge
      
      - run: ./mvnw package test
      
      - save_cache:
          key: neuronbridge-java-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

  build-search-nodejs:
    working_directory: ~/neuronbridge-services/search
  
    docker:
      - image: cimg/node:18.12.0

    steps:
      - checkout:
          path: ~/neuronbridge-services

      - restore_cache:
          keys: 
            - neuronbridge-nodejs-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - neuronbridge-nodejs
      
      - run: npm install
      
      - save_cache:
          key: neuronbridge-nodejs-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run: npm test
      - run: npx eslint src/main/nodejs

workflows:
  version: 2
  build:
    jobs:
      - build-search-java:
          filters:
            branches:
              only: master
      - build-search-nodejs:
          filters:
            branches:
              only: master
