org: janelia
service: neuronbridge-cognito


useDotenv: true


custom:
  org: ${opt:org, self:org}
  version: ${file(./package.json):version}
  # determines if users can create their own account on a site
  disableAccountCreation: ${file(../config.yml):config.disableAccountCreation}
  userPoolName: ${self:custom.org}-${self:service}-userPool-${self:provider.stage}
  userPoolClientName: ${self:custom.org}-${self:service}-userPoolClient-${self:provider.stage}
  identityPoolName: ${self:custom.org}-${self:service}-idPool-${self:provider.stage}
  existingUserPoolId: ${env:USER_POOL_ID, ''}
  existingUserPoolClientId: ${env:USER_POOL_CLIENT_ID, ''}
  existingIdentityPoolId: ${env:IDENTITY_POOL_ID, ''}
  newUserPoolId: !Ref CognitoUserPool
  newUserPoolClientId: !Ref CognitoUserPoolClient
  newIdentityPoolId:  !Ref CognitoIdentityPool
  userPoolId: ${self:custom.existingUserPoolId self:custom.newUserPoolId}
  userPoolClientId: ${self:custom.existingUserPoolClientId, self:custom.newUserPoolClientId}
  identityPoolId: ${self:custom.existingIdentityPoolId, self:custom.newIdentityPoolId}
  # settings needed for setting policies
  searchBucket: ${file(../config.yml):config.searchBucket}
  dataBucket: ${file(../config.yml):config.dataBucket}
  downloadBucket: ${file(../config.yml):config.downloadBucket}
  pppmBucket: ${env:PPPM_DATA_BUCKET, file(../config.yml):config.pppmBucket}
  libraryBucketSuffixes:
    prod: ''
    val: ''
    other: -${self:provider.stage}
  libraryStageBucket: janelia-flylight-color-depth${self:custom.libraryBucketSuffixes.${self:provider.stage}, self:custom.libraryBucketSuffixes.other}
  libraryThumbStageBucket: janelia-flylight-color-depth-thumbnails${self:custom.libraryBucketSuffixes.${self:provider.stage}, self:custom.libraryBucketSuffixes.other}
  libraryBucket: ${env:IMAGE_DATA_BUCKET, self:custom.libraryStageBucket}
  libraryThumbnailsBucket: ${env:IMAGE_THUMBNAILS_BUCKET, self:custom.libraryThumbStageBucket}


provider:
  name: aws
  architecture: arm64
  runtime: nodejs18.x
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, "dev"}
  deploymentBucket:
    name: janelia-serverless-deployments
    blockPublicAccess: true
  tags:
    PROJECT: NeuronBridge
    VERSION: ${self:custom.version}
    DEVELOPER: ${env:USER}
  stackTags:
    PROJECT: NeuronBridge
    VERSION: ${self:custom.version}
    DEVELOPER: ${env:USER}
    STAGE: ${self:provider.stage}


resources:
  - ${file(sls_resources/cognito-pools.yml)}
