Parameters:
  WithSearchBucket:
    Type: String
    AllowedValues:
      - true
      - false
    Default: false
    Description: Enter true if SearchBucket does not exist
Conditions:
  CreateSearchBucket: !Equals
    - !Ref WithSearchBucket
    - true
Resources:
  SearchBucket:
    Type: AWS::S3::Bucket
    Condition: CreateSearchBucket
    DeletionPolicy: Retain
    Properties:
      BucketName: ${self:custom.searchBucket}
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
            - GET
            - HEAD
            - PUT
            - POST
            - DELETE
            AllowedHeaders:
            - "*"
            ExposedHeaders:
            - "x-amz-server-side-encryption"
            - "x-amz-request-id"
            - "x-amz-id-2"
            - "ETag"
            AllowedOrigins:
            - "*.janelia.org:3000"
            - "*.janelia.org"
            - "*.hhmi.org"
            - "*.hhmi.org:3000"
            - Fn::Join:
              - ""
              - - "http://janelia-neuronbridge-web-"
                - ${self:provider.stage}
                - ".s3-website-"
                - ${self:provider.region}
                - ".amazonaws.com"
  DownloadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.downloadBucket}
      LifecycleConfiguration:
        Rules:
          - Id: DeleteRule
            Prefix: ''
            Status: Enabled
            ExpirationInDays: '1'
