Resources:
  preferencesRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: ${self:service}-${self:provider.stage}-preferences
      Description: Allow preferences lambda to read/write DynamoDB
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ${self:service}-${self:provider.stage}-preferences
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                  - "dynamodb:DeleteItem"
                  - "dynamodb:PutItem"
                Resource: !Sub arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:custom.preferencesTable}
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  mailinglistRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: ${self:service}-${self:provider.stage}-mailinglist
      Description: Allow mailinglist lambda to read DynamoDB & cognito pool
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ${self:service}-${self:provider.stage}-mailinglist-dynamodb
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                Resource: !Sub arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:custom.preferencesTable}
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: ${self:service}-${self:provider.stage}-mailinglist-cognito
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "cognito-idp:AdminInitiateAuth"
                  - "cognito-idp:AdminGetUser"
                  - "cognito-idp:ListUsers"
                Resource:
                  - { Fn::Join: [
                    "",
                    [
                      "arn:aws:cognito-idp:",
                      {
                        Ref: "AWS::Region"
                      },
                      ":",
                      {
                        Ref: "AWS::AccountId"
                      },
                      ":userpool/",
                      {
                        Ref: CognitoUserPool
                      }
                    ]
                  ]}
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"




  announcementsRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: ${self:service}-${self:provider.stage}-announcements
      Description: Allow annotations lambda to read/write DynamoDB
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ${self:service}-${self:provider.stage}-announcements
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                  - "dynamodb:DeleteItem"
                  - "dynamodb:PutItem"
                Resource: !Sub arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:custom.announcementsTable}
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"


  publishedNames:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: ${self:service}-${self:provider.stage}-publishedNames
      Description: Allow published names lambda to read/write DynamoDB
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ${self:service}-${self:provider.stage}-publishedNames
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                Resource: !Sub arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:custom.publishedNamesTable}
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  userMigrationRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: ${self:service}-${self:provider.stage}-userMigrationRole
      Description: Allows migration lambda to access data user data in cognito
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
         - PolicyName: userMigrationLogging
           PolicyDocument:
             Version: '2012-10-17'
             Statement:
               - Effect: Allow
                 Action:
                   - logs:CreateLogGroup
                   - logs:CreateLogStream
                   - logs:PutLogEvents
                 Resource: "*"
         - PolicyName: userMigration
           PolicyDocument:
             Version: '2012-10-17'
             Statement:
               - Effect: Allow
                 Action:
                   - "cognito-idp:AdminInitiateAuth"
                   - "dynamodb:Scan"
                   - "dynamodb:Query"
                   - "cognito-idp:AdminGetUser"
                 Resource: !Sub arn:aws:cognito-idp:${self:provider.region}:${AWS::AccountId}:userpool/${self:custom.oldUserPoolId}
  dataMigrationRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: ${self:service}-${self:provider.stage}-dataMigrationRole
      Description: Allow the data migration code to read/write DynamoDB
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ${self:service}-${self:provider.stage}-dataMigration
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:Scan"
                  - "dynamodb:DeleteItem"
                  - "dynamodb:Query"
                Resource: !Sub arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:custom.oldSearchTable}
              - Effect: Allow
                Action:
                  - "dynamodb:Scan"
                  - "dynamodb:PutItem"
                  - "dynamodb:Query"
                Resource: !Sub arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:custom.searchTable}
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - "cognito-idp:AdminInitiateAuth"
                  - "cognito-idp:AdminGetUser"
                  - "cognito-idp:ListUsers"
                Resource:
                  - { Fn::Join: [
                    "",
                    [
                      "arn:aws:cognito-idp:",
                      {
                        Ref: "AWS::Region"
                      },
                      ":",
                      {
                        Ref: "AWS::AccountId"
                      },
                      ":userpool/",
                      {
                        Ref: CognitoUserPool
                      }
                    ]
                  ]}
                  - !Sub arn:aws:cognito-idp:${self:provider.region}:${AWS::AccountId}:userpool/${self:custom.oldUserPoolId}
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectTagging
                  - s3:ListBucket
                Resource:
                  - "arn:aws:s3:::${self:custom.oldSearchBucket}"
                  - "arn:aws:s3:::${self:custom.oldSearchBucket}/*"
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectTagging
                Resource:
                  - "arn:aws:s3:::${self:custom.searchBucket}/"
                  - "arn:aws:s3:::${self:custom.searchBucket}/*"
